<?xml version="1.0" encoding="utf-8" ?> 
<DUMMY>
  <DEFINE>
    <!-- standard size -->
    <CUS_BLUE_KNOB base_type="IMAGE_PARAM_KNOB" pixel_range="128" image="$THEME_PATH$/knobs/knob.png" image_focus="$THEME_PATH$/knobs/knob_hover.png" image_pushed="$THEME_PATH$/knobs/knob_hover.png" images_count="127" positions_count="127" image_orientation="vertical" cursor="system::hand"/>
    <CUS_BLUE_KNOB_SYM base_type="IMAGE_PARAM_KNOB" pixel_range="128" image="$THEME_PATH$/knobs/knob_sym.png" image_focus="$THEME_PATH$/knobs/knob_sym_hover.png" image_pushed="$THEME_PATH$/knobs/knob_sym_hover.png" images_count="127" positions_count="127" image_orientation="vertical" cursor="system::hand"/>    
     <CUS_RED_KNOB base_type="IMAGE_PARAM_KNOB" pixel_range="128" image="$THEME_PATH$/knobs/knob_red.png" image_focus="$THEME_PATH$/knobs/knob_red_hover.png" image_pushed="$THEME_PATH$/knobs/knob_red_hover.png" images_count="127" positions_count="127" image_orientation="vertical" cursor="system::hand"/>
    <CUS_RED_KNOB_SYM base_type="IMAGE_PARAM_KNOB" pixel_range="128" image="$THEME_PATH$/knobs/knob_red_sym.png" image_focus="$THEME_PATH$/knobs/knob_red_sym_hover.png" image_pushed="$THEME_PATH$/knobs/knob_red_sym_hover.png" images_count="127" positions_count="127" image_orientation="vertical" cursor="system::hand"/>    
 
     <!-- small size -->
    <CUS_SMALL_BLUE_KNOB base_type="IMAGE_PARAM_KNOB" pixel_range="128" image="$THEME_PATH$/knobs/small_knob.png" image_focus="$THEME_PATH$/knobs/small_knob_hover.png" image_pushed="$THEME_PATH$/knobs/small_knob_hover.png" images_count="127" positions_count="127" image_orientation="vertical" cursor="system::hand"/>
  
     <!-- mini size -->
     <CUS_MINI_BLUE_KNOB base_type="IMAGE_PARAM_KNOB" pixel_range="128" image="$THEME_PATH$/knobs/mini_knob.png" image_focus="$THEME_PATH$/knobs/mini_knob_hover.png" image_pushed="$THEME_PATH$/knobs/mini_knob_hover.png" images_count="127" positions_count="127" image_orientation="vertical" cursor="system::hand"/>
    <CUS_MINI_BLUE_KNOB_SYM base_type="IMAGE_PARAM_KNOB" pixel_range="128" image="$THEME_PATH$/knobs/mini_knob_sym.png" image_focus="$THEME_PATH$/knobs/mini_knob_sym_hover.png" image_pushed="$THEME_PATH$/knobs/mini_knob_sym_hover.png" images_count="127" positions_count="127" image_orientation="vertical" cursor="system::hand"/>    
     <CUS_MINI_RED_KNOB base_type="IMAGE_PARAM_KNOB" pixel_range="128" image="$THEME_PATH$/knobs/mini_knob_red.png" image_focus="$THEME_PATH$/knobs/mini_knob_red_hover.png" image_pushed="$THEME_PATH$/knobs/mini_knob_red_hover.png" images_count="127" positions_count="127" image_orientation="vertical" cursor="system::hand"/>
    <CUS_MINI_RED_KNOB_SYM base_type="IMAGE_PARAM_KNOB" pixel_range="128" image="$THEME_PATH$/knobs/mini_knob_red_sym.png" image_focus="$THEME_PATH$/knobs/mini_knob_red_sym_hover.png" image_pushed="$THEME_PATH$/knobs/mini_knob_red_sym_hover.png" images_count="127" positions_count="127" image_orientation="vertical" cursor="system::hand"/>    
  </DEFINE>
</DUMMY>