<?xml version="1.0" encoding="utf-8" ?>
 <DUMMY>
 <!-- the 4 screws -->
   <CELL v_margin="6" h_margin="4" v_align="top" h_align="left">
      <IMAGE image="screw_small.bmp" />
   </CELL>
   <CELL v_margin="6" h_margin="6" v_align="top" h_align="right">
      <IMAGE image="screw_small.bmp" />
   </CELL>
   <CELL v_margin="6" h_margin="4" v_align="bottom" h_align="left">
      <IMAGE image="screw_small.bmp" />
   </CELL>
   <CELL v_margin="6" h_margin="6" v_align="bottom" h_align="right">
      <IMAGE image="screw_small.bmp" />
   </CELL>
   <!-- the two handles on top of the design, aligned to left and right-->
   <COLUMN h_align="left" height="100%" h_margin="7" v_margin="10">
		 <CELL height="20" />
         <IMAGE_GROUP_BOX image="handle.bmp" height="97%" width="40" />
   </COLUMN>
   <COLUMN h_align="right" height="100%" v_margin="10">
        <CELL height="20" />
        <IMAGE_GROUP_BOX image="handle.bmp" height="97%" width="23" />
   </COLUMN>
 </DUMMY>